# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cyslab-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://conatainerregistriescyslabbackend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_40414979cbca4ad193c66cbeb824ddcc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fb5a2b45f6a94dedab402cd96a811e08 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: conatainerregistriescyslabbackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40414979cbca4ad193c66cbeb824ddcc }}/cyslab-deployment:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          GITHUB_USERNAME=${{ secrets.Production_Github_Username }}
          GITHUB_PASSWORD=${{ secrets.Production_Github_Password }}
          LARAVEL_APP_NAME=cyslab
          LARAVEL_APP_ENV=production
          LARAVEL_APP_DEBUG=false
          LARAVEL_APP_URL=${{ secrets.Production_Laravel_App_Url }}
          LARAVEL_DB_CONNECTION=${{ secrets.Production_Connection_Db }} 
          LARAVEL_DB_HOST=${{ secrets.Production_Host_Db }} 
          LARAVEL_DB_PORT=${{ secrets.Production_Port_Db }}  
          LARAVEL_DB_DATABASE=${{ secrets.Production_Name_Db }} 
          LARAVEL_DB_USERNAME=${{ secrets.Production_User_Db }}  
          LARAVEL_DB_PASSWORD=${{ secrets.Production_Password_Db }}  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cyslab-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad7f47c8028d4b0692dd06604f165f2b }}
        images: 'conatainerregistriescyslabbackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40414979cbca4ad193c66cbeb824ddcc }}/cyslab-deployment:${{ github.sha }}'